############ CI/CD Pipeline ############
# This pipeline automates the Expo project build and OTA update process.
# It is configured to run only when manually triggered via GitHub Actions UI
# (using 'workflow_dispatch'), to preserve monthly build credits on the free Expo plan.
#
# Steps:
# - Install dependencies
# - Install EAS CLI
# - Run optional linting and tests
# - (Optional) Prebuild step for native code sync
# - Trigger an Android APK build via EAS
# - Push an OTA update to the specified branch (main)
#
# Note: The iOS build is excluded to avoid credential setup errors and because it's not needed.
########################################

name: Expo CI/CD Pipeline

on:
  workflow_dispatch: # ⬅️ start the workflow manually from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Run Lint
        run: npm run lint || echo "No lint script defined"

      - name: Run Tests
        run: npm test || echo "No tests found"

      - name: Expo Prebuild (optional)
        run: npx expo prebuild --non-interactive || echo "Skip if not needed"

      - name: EAS Build (Android APK only)
        run: eas build --platform android --profile android-apk --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: EAS Update (OTA)
        run: eas update --branch main --message "OTA update from GitHub Actions"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
